Title="bityuan"
FixTime=false

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "debug"
logConsoleLevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false

[blockchain]
dbPath="datadir"
dbCache=64
batchsync=false
isRecordBlockSequence=false
enableTxQuickIndex=true
# 升级storedb是否重新执行localdb，bityuan主链升级不需要开启，平行链升级需要开启
enableReExecLocal=false
# 使能精简localdb
enableReduceLocaldb=true
# 是否禁止分片功能，默认开启分片功能
disableShard=false
# 使能从P2pStore中获取数据
enableFetchP2pstore=true

[p2p]
types=["dht"]
dbPath="datadir/addrbook"
dbCache=4
grpcLogFile="grpc33.log"
#waitPid 等待seed导入
waitPid=false

[p2p.sub.gossip]
port=13802
seeds=[]
isSeed=false
innerSeedEnable=true
useGithub=true
innerBounds=300

[p2p.sub.dht]
#可以自定义设置连接节点
seeds=[]
port=13803
maxConnectNum=40
# 是否配置为全节点模式，全节点保存所有分片数据，种子节点应配置为true
isFullNode=false
#允许连接的最低版本
verLimit="6.8.9"

[p2p.sub.dht.pubsub]
gossipSubDlo=7
gossipSubD=10
gossipSubDhi=20
gossipSubHeartbeatInterval=900
gossipSubHistoryGossip=2
gossipSubHistoryLength=7


[rpc]
jrpcBindAddr="localhost:8801"
grpcBindAddr="localhost:8802"
whitelist=["127.0.0.1"]
jrpcFuncWhitelist=["*"]
grpcFuncWhitelist=["*"]
enableTLS=false
certFile="cert.pem"
keyFile="key.pem"

[rpc.sub.eth]
enable=true
httpAddr="localhost:8546"
httpApi=["eth","web3","personal","admin","net"]
# websocket 绑定地址
wsAddr="localhost:8547"
wsApi=["eth","web3","personal","admin","net"]
#兼容交易返回eth 哈希
enableRlpTxHash=true
#启动快速估算gas
disableQuickGas=false
[mempool]
maxTxNumPerAccount=100

[store]
dbPath="datadir/mavltree"
dbCache=128

[store.sub.mavl]
enableMavlPrefix=true
enableMVCC=false
enableMavlPrune=true
pruneHeight=10000
enableMemTree=true
enableMemVal=true
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000,默认200000
tkCloseCacheLen=200000

[store.sub.kvmvccmavl]
enableMVCCIter=true
enableMavlPrefix=true
enableMVCC=false
enableMavlPrune=true
pruneMavlHeight=10000
enableMVCCPrune=false
pruneMVCCHeight=10000
enableMemTree=true
enableMemVal=true
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000,默认200000
tkCloseCacheLen=200000

[wallet]
dbPath="wallet"
dbCache=16

[wallet.sub.ticket]
minerdisable=false
minerwhitelist=["*"]

[exec]
enableStat=false
enableMVCC=false
[exec.sub.token]
saveTokenTxList=false

[exec.sub.evm]
#是否开启升级
nonceUpGrade=false
#升级路径
upgradeUrl="cloud.bityuan.com:8802"
debugEvmTxLog=false
[metrics]
#是否使能发送metrics数据的发送
enableMetrics=false
#数据保存模式
dataEmitMode="influxdb"

[metrics.sub.influxdb]
#以纳秒为单位的发送间隔
duration=1000000000
url="http://influxdb:8086"
database="chain33metrics"
username=""
password=""
namespace=""
